/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package openapi

type AppStoreImageHubResp struct {
	HubPassword string `json:"hub_password,omitempty"`
	HubUrl string `json:"hub_url,omitempty"`
	HubUser string `json:"hub_user,omitempty"`
	Namespace string `json:"namespace,omitempty"`
}
