/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package openapi

import "encoding/json"

type AutoSsl struct {
	Enable bool            `json:"enable,omitempty"`
	Value  json.RawMessage `json:"value,omitempty"`
}
