/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package openapi

type AppModifyInfo struct {
	BuildSource *AppChangeBuildSource `json:"build_source"`
}

type AppChangeBuildSource struct {
	Version string `json:"version"`
}
