/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package openapi

type AutoSsl struct {
	Enable bool   `json:"enable,omitempty"`
	Value  string `json:"value,omitempty"`
}
