/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package openapi

type PostHttpGatewayRule struct {
	// 证书id
	CertificateId int32 `json:"certificate_id,omitempty"`
	// 绑定端口
	ContainerPort int32 `json:"container_port"`
	// 域名cookie
	DomainCookie string `json:"domain_cookie,omitempty"`
	// 域名header
	DomainHeader string `json:"domain_header,omitempty"`
	// 域名
	DomainName string `json:"domain_name"`
	// 域名路径
	DomainPath string `json:"domain_path,omitempty"`
	// 规则扩展
	RuleExtensions []string `json:"rule_extensions,omitempty"`
	// 应用组件id
	ServiceId string `json:"service_id"`
	TheWeight int32 `json:"the_weight,omitempty"`
	// 是否开放
	WhetherOpen bool `json:"whether_open,omitempty"`
}
