/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package openapi

type AppCopyC struct {
	Services []AppCopyModify `json:"services"`
	// 应用id
	TargetAppId int32 `json:"target_app_id"`
	// 数据中心名称
	TargetRegionName string `json:"target_region_name"`
	// 团队名称
	TargetTeamName string `json:"target_team_name"`
}
