/*
 * Rainbond Open API
 *
 * Rainbond open api
 *
 * API version: v1
 * Contact: barnett@goodrain.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package openapi

type AppCopyModify struct {
	Change *AppModifyInfo `json:"change,omitempty"`
	// id
	ServiceId string `json:"service_id"`
}
